### ISSUE TITLE
version mismatch kodi-002-sound-fix.patch 

### ISSUE THREAD

**Issue by lymon66** [jernejsk/OpenELEC-OPi2#10]
patch relies on version 16.0-beta2-64de219 while current version is 16.0-beta5-19fc4fa.

Is this patch still needed ?

**Comment by jernejsk** [comment]
First folder name in a patch is not important, so this is not an issue. You can try to remove it and test it. Please report if you will try.

**Comment by lymon66** [comment]
ok, just tried it and patch is still needed. issue can be closed.
