### ISSUE TITLE
Add Multi-language Support 

### ISSUE THREAD

**Issue by RSAspace** [jernejsk/OpenELEC-OPi2#14]
Plese add standard OpenElec languages set.

**Comment by jernejsk** [comment]
What do you mean by "standard OpenElec languages set"? Source code is basically the same apart some drivers and systemd.

**Comment by RSAspace** [comment]
If I build the image from the repository , it will choose the language of the interface ? Just your images in MEGA only include English.

Отправлено с Mi Phonejernejsk notifications@github.com | От: 2 февр. 2016 г. 22:30 | Сообщение:What do you mean by "standard OpenElec languages set"? Source code is basically the same apart some drivers and systemd.

**Comment by jernejsk** [comment]
Please see this: http://openelec.tv/forum/110-update-openelec/79007-after-update-on-6-0-only-english-language
http://kodi.wiki/view/HOW-TO:Install_languages_offline
