### ISSUE TITLE
while compiling i get a error

### ISSUE THREAD

**Issue by jteeuw** [jernejsk/OpenELEC-OPi2#15]
while compiling i get a error :

UNPACK   ntfs-3g_ntfsprogs

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: **\* [image] Error 2

I use ubuntu 14.04.03 (32bit)

**Comment by jernejsk** [comment]
Try to open this file: http://tuxera.com/opensource/ntfs-3g_ntfsprogs-2015.3.14.tgz
If it works, then delete sources/ntfs-3g_ntfsprogs/ folder and try again. If any of those steps fail, then it's upstream problem and won't be fixed by me.
