### ISSUE TITLE
Sata doesn't work on OPiPlus

### ISSUE THREAD

**Issue by galeots** [jernejsk/OpenELEC-OPi2#17]
My sata non work not power sata!
HELP!

**Comment by jernejsk** [comment]
I unfortunately don't have Plus version, so there is not much I can help you with.

**Comment by jernejsk** [comment]
I figured out what needs to be done to fix this. Just wait a bit.

**Comment by galeots** [comment]
Thank! then you will create a patch!?

**Comment by jernejsk** [comment]
Yes, but it will take some time.

**Comment by jernejsk** [comment]
Please test this image: https://mega.nz/#!pURFxA5D!J-LNXV9hJ6wvO7vwLJVot4Bw_Rw2dESa-qOPJZGf2E8

**Comment by jernejsk** [comment]
Disregard, I must fix another issue

**Comment by jernejsk** [comment]
Now it should work, but I'm not satisfied with solution: https://mega.nz/#!RA4khbYQ!nYcVRgEoS52ZMlu2HWulEoQ8YBfCyLKgbpXtoqmaDVk

**Comment by galeots** [comment]
I'm testing now! I was at work...
What would you have changed !?

**Comment by galeots** [comment]
ok does the fix! 
you can copy the debian operating !?
 I did not succeed because you say that you are not satisfied?

**Comment by jernejsk** [comment]
Ok, so we can close the issue?  I'm not satisfied with the way how it is implemented, but I will survive. Sorry, I'm not sure what do you mean with Debian.

**Comment by galeots** [comment]
You can close .. you can see how it is built on Debian. the sata booting differently.
