### ISSUE TITLE
HW deinterlacing possible  ??

### ISSUE THREAD

**Issue by piotrasd** [jernejsk/OpenELEC-OPi2#2]
After some time will be possible HW deinterlacing ??
this is special needed for LiveTV :/

**Comment by jernejsk** [comment]
Yeah, sure. However, SW deinterlacing should work for now?

**Comment by piotrasd** [comment]
I just orderd OPI2 .... so later i will be testing, but from expirance i know software Deinterlace for 1080i material jak LiveTV is not enough :(, or very week or very high load CPU

**Comment by jernejsk** [comment]
Valid concern. I would like to make direct rendering first and deinterlacing directly after.

**Comment by jernejsk** [comment]
Can you please check if the latest patch on the orangepi forum works for you? I included HW deinterlace support.

**Comment by jernejsk** [comment]
With commit 7dbbcfb1bac5b96313a7b00c2d69de2c63959d3c I consider this as implemented.
