### ISSUE TITLE
Potential overvolting/overheating on Orange Pi One

### ISSUE THREAD

**Issue by ThomasKaiser** [jernejsk/OpenELEC-OPi2#22]
Please be aware that recent research showed that the new voltage regulation method on Orange Pi One might not switch between 1.1V and 1.3V but instead way larger voltages that exceed maximum specs for H3 and lead to overheating.

And please be also aware that thermal throttling might not work as expected when combining a) mainline u-boot with kernel 3.4 and b) depending on DRAM clockspeed.

http://irclog.whitequark.org/linux-sunxi/2016-02-17#15525969;
http://linux-sunxi.org/Orange_Pi_One
http://kaiser-edv.de/tmp/4U4tkD/Orange_Pi_One_Comparison.png
https://github.com/igorpecovnik/lib/pull/152

**Comment by ThomasKaiser** [comment]
Oops, just realised that you also ship now with fex settings that add the risk to burn H3 on top. This is 5°C-10°C more than the defaults:

ths_trip1_0 = 80
ths_trip1_1 = 85
ths_trip1_2 = 95
ths_trip1_3 = 95
ths_trip1_4 = 100
ths_trip1_5 = 105
...
ths_trip2_0 = 110

**Comment by jernejsk** [comment]
Thanks for pointing this out. I will soon update all fex settings. 

FYI, [this](http://lists.denx.de/pipermail/u-boot/2016-February/245097.html) **might** have some impact on CPU stability.

**Comment by jernejsk** [comment]
Are kernel patches tested/recommended?

**Comment by ThomasKaiser** [comment]
Regarding the above u-boot patch it's more about boot problems based on my understanding: http://forum.armbian.com/index.php/topic/617-wip-support-for-the-upcoming-orange-pi-one/?p=5238

Regarding the thermal stuff only fex adjustments (disable switching to the higher voltage for the OPi One and decreasing the ths values for all boards) are necessary at the moment. Maybe someone comes up with a fix for the wrong thermal readouts (seems clock related). The aforementioned fixes are especially necessary for OPi One since in combination (overvolting and thermal throttling happening too late) it might really be a bit dangerous.

BTW: You included a few script.bin fixes a few days ago that change GPIO pins a lot. Care to ask the author to explain somewhere (publicly -- i.e. not in OPi forum) what/why he has adjusted? :)

**Comment by jernejsk** [comment]
Ok, I will include those patches for OPiOne.

I'm the author of those changes. Basically nothing special, just reconfiguring GPIOs to 1-wire and SPI. Did I miss something? That is already off-topic :)

I will join your forum so we don't need to abuse issues for general talk.

**Comment by ThomasKaiser** [comment]
I fear that only my Orange Pi One is somewhat defective and suffers from overvolting. A few Armbian users measured voltagea at the test points and they got correct values (1.1V and 1.3V), so my proposed 'fix' is counterproductive since it prevents the One from switching to the higher voltage which is necessary when higher cpufreqs are used. It seems reverting back to defaults would be the better choice: http://linux-sunxi.org/Orange_Pi_One#Normal_dvfs_settings

Sorry for the noise...

**Comment by jernejsk** [comment]
Ok, values are reverted in commit 6dbd4e31281f20cd6738030a9bacdb307930bbe8
