### ISSUE TITLE
hdmi cec not work

### ISSUE THREAD

**Issue by galeots** [jernejsk/OpenELEC-OPi2#23]
Hello!
I was trying the cec but it seems it does not work!
You have to enable something !?
When you upgrade the kernel to the version 4.1?
Thank you

**Comment by jernejsk** [comment]
Currently, there is no CEC driver available or any documentation about HDMI HW. So unless something of these two things change, I can't do anything.

I won't update anytime soon to mainline kernel, unless if you want to be without sound, ethernet, display drivers are not yet merged, etc.
