### ISSUE TITLE
hdmi cec

### ISSUE THREAD

**Issue by galeots** [jernejsk/OpenELEC-OPi2#25]
sorry if I open, but these are the driver!
the cec for hdmi interesting to many, including myself!

https://github.com/orangepi-xunlong/linux-sunxi/tree/orangepi-3.4/drivers/video/hdmi-cec

**Comment by jernejsk** [comment]
I'm very well aware of this source. However, it is for different chips - A10, A20, etc. Even then, show me some image which successfully uses those driver.

**Comment by galeots** [comment]
I'm looking for information about...
integration driver hdmi-cec not work!?
http://www.cubieforums.com/index.php?topic=1140.0

**Comment by jernejsk** [comment]
If you find any useful information, you can reopen the issue.
