### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by galeots** [jernejsk/OpenELEC-OPi2#28]
after turning the system off the power button does not work, unofficial OpenELEC not present or not working, implement addons torrent as rutorrent

**Comment by jernejsk** [comment]
I never claimed that power button works and it is still work in progress. Currently, I really don't have a time for working on repositories, so this would have to wait.

**Comment by galeots** [comment]
add unofficial OpenELEC pls not work end implement addons torrent as rutorrent

**Comment by jernejsk** [comment]
I will close this as won't fix, because on orange pi forum an unofficial repo can be found with transmission torrent client.
