### ISSUE TITLE
cedarx-mpeg2 broken in r21674

### ISSUE THREAD

**Issue by lymon66** [jernejsk/OpenELEC-OPi2#3]
tested several codecs in version r21674:

cedarx-divx5 : ok (several different resolutions tested)
cedarx-xvid: ok (several different resolutions tested)
cedarx-h264: ok (no transparent stripes anymore, several different resolutions tested)
cedarx-h265: ok (no green stripes anymore, several different resolutions tested)
ff-mpeg2video: ok

only problem I have now is with cedarx-mpeg2
Image is overly stretched for some reason  and only shows the top half of the image (stretched to full screen)
I can't correct it with using custom settings....the lower half will still be missing
overscan on/off doesn't make a difference

checked with version r21672 and here it works fine.
So something broke with the latest changes in the cedarx-mpeg2 codec..

**Comment by jernejsk** [comment]
Can you please give me the link to the problematic video?

**Comment by lymon66** [comment]
here's a short example of a problematic video.

https://github.com/lymon66/ORANGEPI-PC/blob/master/Openelec/Joins-BBC-News.2015-12-16.mkv?raw=true

**Comment by jernejsk** [comment]
I disabled green stripe fix for interlaced videos in 77b67b442cb4310ceef1a4dedfd3a54ac9c4a2dd. This is just temporary until HW deinterlacing and direct rendering is implemented.
