### ISSUE TITLE
Porting changes to Kodi

### ISSUE THREAD

**Issue by TerrorFactor** [jernejsk/OpenELEC-OPi2#31]
I don't have high hopes for this, but could the HW decoding etc. be ported to Kodi itself?
I am trying to use my orange pi as an all in one box (mainly downloadbox + media center), but OpenElec doesn't lend itself for that. 

Armbian + Kodi works good, but there is no HW decoding, so you're forced to use an external player, so the remote and resuming etc doesn't work that way.

**Comment by jernejsk** [comment]
You can take my Kodi patch and try to port it over to X11 environment, but I'm not sure how much work would be needed. Take a look at projects/H3/patches/kodi

**Comment by gitchomik** [comment]
@TerrorFactor: If @jernejsk successfully create OpenELEC with mainline kernel you will be able to use OpenELEC + Docker + (for example) Ubuntu. Then you'll do what you want.

**Comment by TerrorFactor** [comment]
@gitchomik There's a docker plugin in the unofficial repository (https://github.com/gitchomik/OPI_Openelec.unofficial-addons.repo). Good idea, will give it a shot :)

**Comment by jernejsk** [comment]
@TerrorFactor Please be aware that mainline branch won't be able to run Kodi for quiet some time. Are you ok with closing this issue?

**Comment by TerrorFactor** [comment]
I am, thank you :) If I had the skills, I'd give it a go, trying to port it myself, but alas. Thank you for the great work!
