### ISSUE TITLE
Docker support in mainline kernel

### ISSUE THREAD

**Issue by gitchomik** [jernejsk/OpenELEC-OPi2#32]
Hi,
I saw that you create branch with mainline kernel.
I successfully build Docker addon for Orange Pi OpenELEC
(https://github.com/gitchomik/OPI_Openelec.unofficial-addons.repo)
So, **please add support in kernel for Docker**.

You can modify (https://github.com/docker/docker/blob/master/contrib/check-config.sh)
to check your kernel .config for minimal requirements.

See also: 
https://github.com/OpenELEC/OpenELEC.tv/pull/4256/commits/727f4e35b06e6d7de53734b5366c0bc3d69eb66a
https://github.com/OpenELEC/OpenELEC.tv/pull/4273/commits/fce741a81e4a872ba23e75c6c148bb92404538f7
https://github.com/OpenELEC/OpenELEC.tv/pull/4273/commits/0f63836e3ba26b794ad04af476fc116dc3ab0a00
https://github.com/OpenELEC/OpenELEC.tv/pull/4273/commits/03d75dac95f7c85031121e5e8788573ba6a0fe25
https://github.com/OpenELEC/OpenELEC.tv/pull/4541/commits/5f04c59d4c38b79694e08b98c199f0bfc1a4baf1
https://github.com/OpenELEC/OpenELEC.tv/pull/4577/commits/4ff2929591e33b08caf093b57d2790830c308c21

Regards!

**Comment by jernejsk** [comment]
I enabled all kernel options which were reported mandatory by the script and were missing.

**Comment by gitchomik** [comment]
@jernejsk, thanks a lot, I compared your changes with with the version of Rpi and it looks good to me.
