### ISSUE TITLE
sata slow

### ISSUE THREAD

**Issue by galeots** [jernejsk/OpenELEC-OPi2#37]
sata slow transfer, usb modality good
problem in kernel?

**Comment by jernejsk** [comment]
What is slow for you? Check https://linux-sunxi.org/Xunlong_Orange_Pi_Plus#SATA and http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=788&fromuid=29411 

The most meaningful comment for 3.4 kernel from OrangePi forum is:

> As I said this USB-SATA bridge is slower than a "simple" USB-Harddisk.

**Comment by galeots** [comment]
sata 6mb/s usb  15mb/s

**Comment by jernejsk** [comment]
While this is a bit off topic, but it is connected to SATA nevertheless.

@galeots, can you test this change in opiplus.fex:
Replace

```
[usbc3]
;usb_drv_vbus_gpio   = port:PG11<1><default><default><1>
usb_drv_vbus_gpio   = 
```

with

```
[usbc3]
usb_drv_vbus_gpio   = port:PG11<1><default><default><1>
```

I'm interested if SATA works then? In the latest image, that is.

**Comment by galeots** [comment]
@jernejsk not work solution

**Comment by jernejsk** [comment]
Ok, next week I'll borrow PLUS board and try to fix the issue.

on topic: I really have no idea what can be done to speed up things. I'm affraid that there is nothing really.

**Comment by jernejsk** [comment]
@galeots, please check #44 for details on SATA and ethernet issue. Could you please test SATA speeds again with image mentioned in #44 and report values? I'm affraid that I can't do anything...

**Comment by galeots** [comment]
@jernejsk, SATA works now but I have not tested the speed.
there is a problem with the time I have left in operation in January 1970 time zone does not work.
video from a random black screens now because kernel new!?

**Comment by jernejsk** [comment]
Please open new issues if they are unrelated to SATA.

**Comment by galeots** [comment]
@jernejsk you not fixed release for sata. i have completed not working new release!

**Comment by jernejsk** [comment]
SATA port works just ok, I tested it and you tested it. Did you use NEW build instructions? Check FAQ.

**Comment by galeots** [comment]
@jernejsk Ah ok where is the FAQ link?

**Comment by jernejsk** [comment]
Check orangepi forum.

**Comment by galeots** [comment]
@jernejsk link pls!

**Comment by pdefreitas** [comment]
Related with #43. This thing of having information in multiple places is very annoying.

@galeots the link you requested is this: http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=1077

Hope that helps.

**Comment by jernejsk** [comment]
So nothing to fix, closing.
