### ISSUE TITLE
Build error: 404 on sqlite package

### ISSUE THREAD

**Issue by markh-de** [jernejsk/OpenELEC-OPi2#39]
Hi,

building the image (fresh build environment) fails with 404 on the sqlite source package:

`Cant't get sqlite sources : https://www.sqlite.org/2016/sqlite-autoconf-3120000.tar.gz`

And indeed, the version seems to be invalid (URL is 404, `sqlite-autoconf-3120200.tar.gz` seems to be the right one). Grepping the sources for `sqlite-autoconf-` or the version string did not lead me to the right point. So, what do I need to fix the URL in order to successfully retrieve the package?

Thanks in advance!

**Comment by jernejsk** [comment]
I merged latest changes which also solve this issue.
