### ISSUE TITLE
change default audio output to sndhdmi in guisettings.xml

### ISSUE THREAD

**Issue by lymon66** [jernejsk/OpenELEC-OPi2#4]
Currently the initial default audio output in the uenv.txt points to hdmi.audio=EDID:0, but kodi overrides this to the analog audio (jack port)

Can you add the following line in packages/mediacenter/kodi/config/guisettings.xml  to correct this and make sndhdmi the initial kodi default audio output?

```
<audiooutput>
      <audiodevice>ALSA:sysdefault:CARD=sndhdmi</audiodevice>
</audiooutput>
```

**Comment by jernejsk** [comment]
This is solved with the merged pull request.
