### ISSUE TITLE
OrangePi Plus show can't access tty...

### ISSUE THREAD

**Issue by Saljack** [jernejsk/OpenELEC-OPi2#41]
Hi I tried to build image for OrangePi Plus. I copied image on SD Card. If I have keyboard in usb, OrangePi does not boot (no led diod). I used prebuild image for OrangePi Plus from official forum with the same result. When I removed keyboard it started boot (green led diod switched on) and splash screen showed up. There was "sh: can't access tty: job control turned off" on screen. I tried image for OrangePi PC and this image worked but without usb support (keyboard and mouse didn't work). Prebuild images  created on 2016/3/22 works good. Thanks for help.

**Comment by jernejsk** [comment]
Interesting. What about 2016/4/25? Just to confirm, you always flashed clean image? I updated to newer kernel in 2016/4/25, which resolves some annoying issues, but obviously introduces some new.

Can you please test this:
1. Flash latest clean OPiPC image
2. Interrupt U-Boot autoboot
3. Execute following commands:

```
gpio set PL10
setenv machid 1029
setenv bootm_boot_mode sec
setenv bootargs console=ttyS0,115200 boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2 consoleblank=0 noram board=opiplus
fatload mmc 0 0x43000000 opiplus.fex
fatload mmc 0 0x42000000 KERNEL
bootm 0x42000000
```

NOTE: First line should enable USB ports.

I'm interested what is the outcome. It should tell us if the problem lies in kernel or u-boot/kernel incompatibility.

**Comment by jernejsk** [comment]
I just found some mistake in opiplus.fex and opi2.fex (previously known as script.bin). Could you fix those values and test again:

```
[usbc0]
usb_id_gpio         = port:PG12<0><1><default><default>
usb_det_vbus_gpio   = port:PG12<0><1><default><default>
```

**Comment by Saljack** [comment]
[2016/3/22] works ok
[2016/4/25] doesn't work show error
2016-04-28 - doesn't work hangs on splash

I will try it with fix opiplus.fex and I will let you know.

**Comment by Saljack** [comment]
Hi after changes in opiplus.fex its working. Thanks for your help.

**Comment by jernejsk** [comment]
Great. I will close it after I will fix it in code. Can you please test suspend/resume via power button?

**Comment by Saljack** [comment]
Suspend/resume doesn't work. If I press power button red led switch on. Board doesn't resume anymore. This wasn't work on Android too (respectivly it resumes work some second after suspend). 

I have found another problem with ethernet. There is no leds on and connection on ethernet connector.

**Comment by jernejsk** [comment]
Please open a new issue.

BTW, I will have Plus board in my hands next week and I can test this then.
