### ISSUE TITLE
OrangePi Plus: ethernet doesn't work

### ISSUE THREAD

**Issue by Saljack** [jernejsk/OpenELEC-OPi2#44]
Ethernet doesn't work in latest versions (build from 16-05-02). There is no led turn on. Wifi works ok but I am not able to connect via ssh with connection refused error (web interface works). Ethernet works in prebuild image from 2016/3/22. Maybe it is something wrong in fex file. Thank you for help

**Comment by jernejsk** [comment]
Probably because of the new kernel. I must check few things. Could you test Armbian 5.10 image if ethernet works? They are using same kernel.

**Comment by Saljack** [comment]
Yes I will try and let you know.

**Comment by Saljack** [comment]
Armbian 5.10.works ok.

**Comment by jernejsk** [comment]
Not sure what was the reason but when I tested it worked. Can you please test latest fex configuration?

**Comment by Saljack** [comment]
It is not work. I made full clear build. Repository was cloned at 23:00 yesterday. It looks like ethernet is disabled. Board doesn't boot if I have usb keyboard pluged in. I had to unplug usb devices and then it starts booting.

**Comment by jernejsk** [comment]
I tested again with clean image freshly flashed on SD card. This is the result: http://pastebin.com/QZdwh528 (scroll to bottom)
Can you test with this image: https://mega.nz/#F!NRIwXJja!hqm9OkB5lE8SwQcc-AtrIw ?

**Comment by Saljack** [comment]
Your image has working ethernet. I might be doing something wrong when I build images. 
My build command is:
`sudo PROJECT=H3 DEVICE=OPiPlus ARCH=arm make image`
Is it correct? 
There is my dmesg and ifconfig http://pastebin.com/iemz8frh . There is problem with eth0 and Interrupt:114. I think you can close this issue. Thank you again.

**Comment by jernejsk** [comment]
Yes, build system changed a bit. DEVICE variable was removed and officially supported SYSTEM is used now. Command should be:

```
PROJECT=H3 SYSTEM=opiplus ARCH=arm make image
```

There is also no need for sudo for quiet some time. Check FAQ sometimes :)

**Comment by Saljack** [comment]
Omg I am idiot sorry
