### ISSUE TITLE
Nanopi M1 support

### ISSUE THREAD

**Issue by seblucas** [jernejsk/OpenELEC-OPi2#47]
Hi,

Not a real issue, more a question. I currently have a nanopi M1 (which is more or less a clone of an Orange Pi One with 512Mb of RAM and an IR receiver)

There is not much difference in the fex file (I managed to boot armbian while being detected as an Orange Pi). Will it be possible to add support for this board ?

I'll download and test your OPiOne build and report here if it already works.

Thanks a lot in advance.

**Comment by jernejsk** [comment]
It seems that OPiOne image should work just as good. Please test and report.

**Comment by seblucas** [comment]
So it works. I only tested with a 720p h264 but it worked fine.

I have more questions now (sorry in advance) : 
- 3 of my 4 cores were killed minutes after boot. Latest Armbian lower cpu frequency instead of killing core. I think it would be better for openelec too.
- my IR seems detected but I didn't manage to use a remote. I'll check a little more

**Comment by jernejsk** [comment]
I checked twice and DVFS settings are the same and cooler table settings are almost the same (one entry less). I really don't know what to set differently. I don't like to support HW which I don't have.

Check FAQ for IR. Remove autostart.sh for IR if you still have one for lircd (old tutorial, which is not applicable anymore).

**Comment by seblucas** [comment]
I checked too and you're right the only difference that I've seen is that with armbian there's a script to resurrect the cores killed if the cooling state goes down
https://github.com/igorpecovnik/lib/blob/master/scripts/sun8i-corekeeper.sh

To keep the temperature down, I've modified the fex to never go to 1200MHz and stay at 1008MHz, maybe I'll even try to use 1.1V instead of 1.3V.

About the IR, I've followed [this tutorial](http://wiki.openelec.tv/index.php/Guide_To_lirc_rpi_GPIO_Receiver) That I used with my Raspberries. I managed to create a lircd.conf with irrecord (so the ir is working well). But after a reboot lircd still doesn't detect my remote. I may have made an error somewhere, I'll check again tomorrow.

**Comment by seblucas** [comment]
To make things clearer you can say that nano pi m1 are supported ;) thanks

**Comment by jernejsk** [comment]
Actually, the only needed command to set up IR is

``` bash
irrecord /storage/.config/lircd.conf
```

Can you install evtest from unofficial repository and provide output?

**Comment by seblucas** [comment]
irrecord was what I used for my last post, irrecord work, but after a reboot kodi doesn't detect it.

I tried [this method](http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=1177&extra=page%3D1) (second post from lymon) and it worked perfectly.

Thanks a lot for your awesome work. I'll close the ticket as all the issues or question I had are solved
