### ISSUE TITLE
Error in Fex file for DVFS

### ISSUE THREAD

**Issue by seblucas** [jernejsk/OpenELEC-OPi2#49]
There was a bug fixed in Armbian about dvfs_table, See https://github.com/igorpecovnik/lib/commit/d6185b560000dda25029727464b8a262d23ee0f9

Your fex files are not ok : the 01100 with a leading 0 is interpreted as octal and gives too high temperatures or instabilities

**Comment by seblucas** [comment]
If you prefer I can make a PR

**Comment by jernejsk** [comment]
Please do, thanks.

**Comment by seblucas** [comment]
Done, see #50 

Sorry for the delay, cloning the repository has taken forever with my crappy ADSL line.

**Comment by jernejsk** [comment]
No problem.
