### ISSUE TITLE
Orange PI PC: Only one USB works

### ISSUE THREAD

**Issue by pdefreitas** [jernejsk/OpenELEC-OPi2#52]
Only one USB port works, suspecting it is related to the fex. CONFIG_USB_SUNXI_OHCI0, CONFIG_USB_SUNXI_OHCI1, CONFIG_USB_SUNXI_OHCI2 are defined to y so that is fine.

**Comment by pdefreitas** [comment]
I don't have my build vm to test this but it might be related to this:
http://forum.armbian.com/index.php/topic/495-solved-debian-on-a20-tv-box-usb-partially-working/

This is missing from the build options:

```
CONFIG_USB_SW_SUNXI_USB=y
CONFIG_USB_SW_SUNXI_USB_MANAGER=y
CONFIG_USB_SW_SUNXI_USB0_OTG=y
CONFIG_USB_SW_SUNXI_USB_DEBUG=y
```

Armbian is actually using this in their build config:
https://github.com/igorpecovnik/lib/blob/b1f6667ea0eb9e9b2b9436d2d083d448bb36998a/config/kernel/linux-sun7i-default.config

**Comment by jernejsk** [comment]
Did you build image for yourself? If you did, did you use new build command? If you didn't, you have actually OPi2 image and this issue is perfectly explainable. You can check this by typing command "cat /proc/cmdline" and check which value board variable have.

**Comment by pdefreitas** [comment]
Actually I've built the image myself. However I was using flag DEVICE=xxx which was wrong. After checking this thread I've saw the flags: http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=1077

SYSTEM=opi2
SYSTEM=opione
SYSTEM=opipc
SYSTEM=opiplus

Cross information is bad practice, I've reported this in issue #43. Orange PI forum seems to be much faster now (don't know if they changed their connectivity), but I'm in Europe with optical fiber connection and it was almost impossible to access their website. As of today it is working fine.

EDIT: I will rebuild the image with this flag and check it.

**Comment by jernejsk** [comment]
Why it would be cross information? It is always in FAQ topic in Orange Pi forums. Everywhere else is not guaranteed to be up to date and it is copied just for convenience. Until this is OrangePi specific, I see no need to move information.

**Comment by pdefreitas** [comment]
If the Orange PI forum go down, have any issue, we github users cannot access any piece of information. Orange PI forum is also not a open space (needs account approval from staff).

This issue is fixed. Thanks.
