### ISSUE TITLE
Is there a way to force to use software decoding for H264?

### ISSUE THREAD

**Issue by dhanar10** [jernejsk/OpenELEC-OPi2#59]
I have some Hi10P H264 and Kodi attempts to play it using CedarX. Of course, it fails. Where can I set to use software decoding for these files? If Kodi can do this automatically, it is better. But manually is ok too for a start.

**Comment by jernejsk** [comment]
Fixed in 4575bc205b224cd34d0d771014d4b3fc0a661a38 Prebuilt images will follow soon.
