### ISSUE TITLE
Is cedarx-vp8 working properly?

### ISSUE THREAD

**Issue by dhanar10** [jernejsk/OpenELEC-OPi2#60]
I stumbled upon a VP8 video. When I played it, Kodi selected cedarx-vp8 to decode it. However, the video is stuttering back and forth. Should VP8 joins WMV1, WMV2, VP6 and VP9 codecs to be SW decoded? My board is an Orange Pi One and I am currently on OpenELEC-H3.arm-7.0-devel-20160602225329-r22840-g4575bc2.

**Comment by jernejsk** [comment]
I tested VP8 sample and everything is fine. Can you provide some, preferably small, sample which would demonstrate effect?

**Comment by dhanar10** [comment]
Here is a 3 minutes sample: https://mega.nz/#!05QDCYqb!7--9i3jW4A2xnkCTbpgo3KvHhaJyi-MgexQGDa2yIwU

You will see some stuttering with the video when played with Kodi in OpenELEC-OPi2. However, with mpv on my desktop, it is playing fine. 

Additional note, this sample may crash Kodi in OpenELEC-OPi2 at the end of the playback. It does not happen in the original full video.

**Comment by jernejsk** [comment]
Unfortunatelly, it seems that some feature of VP8 codec present in your video is not implemented. I can't do anything here unless I receive improved codec which is very unlikely, sorry.
