### ISSUE TITLE
Kernel 4.4 and OrangePi and accelerated video

### ISSUE THREAD

**Issue by faddat** [jernejsk/OpenELEC-OPi2#65]
How'd you do that?  

Seriously, how?  

I'd be thrilled to talk whenever you've got at minute at faddat@gmail.com via Google Hangouts.  

I'm baffled, astonished, and impressed.

**Comment by jernejsk** [comment]
Sorry, currently I'm quiet busy. But you missed one important detail, it is kernel 3.4 from Allwinner and not mainline (4.X).
