### ISSUE TITLE
Protocol NEC

### ISSUE THREAD

**Issue by 6ig6oy** [jernejsk/OpenELEC-OPi2#70]
Hello,
I have a remote control set with the protocol nec for my orange pi-pc.

Your last firmware(20160806192003-r22886-g5828aec) l is enabled only irc protocol
You could not add other protocols as before...

Thank you

**Comment by jernejsk** [comment]
It is, but you have to load it first. For example, add this in autostart.sh (http://wiki.openelec.tv/index.php/Autostart.sh):

modprobe ir-nec-decoder
