### ISSUE TITLE
USB card reader prevents OPiPC booting (ver. 2016-08-06)

### ISSUE THREAD

**Issue by vlna** [jernejsk/OpenELEC-OPi2#72]
At least these devices (card readers) prevents OPiPC booting
1. http://www.aliexpress.com/snapshot/7772612070.html?spm=2114.13010608.0.65.2ikFch&orderId=75941769556683
2. http://www.kingston.com/us/flash/readers/fcr-mrg2

When power is connected no LED is going to light. No HDMI output.

image used: OpenELEC-H3.arm-7.0-devel-20160806192003-r22886-g5828aec-opipc.img

At least first device was used with 2016-05-10 and this install was later manualy updated to version to 2016-06-02. It worked without this issue.

Card reader must be without card - with inserted card OPiPC boots.

**Comment by jernejsk** [comment]
What about an older image?

**Comment by vlna** [comment]
Version 2016-05-10 worked for me, then I updated to version 2016-06-02. I used update file (not fresh install) and it still worked.

**Comment by jernejsk** [comment]
Maybe U-Boot USB has something to do with this issue... What if you update, actually downgrade, to last version which works. Then you untar 2016-08-06 update file and copy over KERNEL and SYSTEM files. Also please delete script.bin and copy over opipc.fex and rename it to script.bin. That way you will be left with old U-Boot but newer system.

**Comment by vlna** [comment]
Fresh OpenELEC-H3.arm-7.0-devel-20160602225514-r22840-g4575bc2-opipc.img boots with empty card reader connected.

I would like to follow test you described but it is not clear for me what to do, where start. Could you explain it with more details.

**Comment by jernejsk** [comment]
1. prepare fresh OpenELEC-H3.arm-7.0-devel-20160602225514-r22840-g4575bc2-opipc.img image.
2. download update file to 2016/08/06
3. extract update file (untar)
4. insert sd card to pc and open FAT partition (512 MB in size)
5. replace KERNEL and SYSTEM files from extracted update file (target/ subfolder)
6. delete script.bin
7. copy over opipc.fex from 3dparty/bootloader subfolder from update file
8. rename opipc.fex to script.bin

you should have newer files on your sd card FAT partition, but same U-Boot

**Comment by vlna** [comment]
OPiPC with empty USB card reader boots with old U-Boot and new KERNEL, SYSTEM and script.bin.

**Comment by jernejsk** [comment]
ok, then I will disable USB in U-Boot and give you update file to test. I would do it anyway as it will speed up booting.

**Comment by jernejsk** [comment]
Can you try this update? Link is valid for 14 days.
 https://transfer.sh/ebKy3/openelec-h3.arm-7.0-devel-20160817211715-r22886-g5828aec.tar

I disabled USB and fix U-Boot update procedure.

**Comment by vlna** [comment]
I updated ver. 2016-08-06 with provided update file and now OPiPC boots even with card reader connected. I think green LED now turns on faster after connecting power than in previous versions.

**Comment by jernejsk** [comment]
Both was intendent. Fixed in 72d778d145aff54deef3f899f6ce07bd2df71006.
