### ISSUE TITLE
HDMI garbage on TV

### ISSUE THREAD

**Issue by vincent-legoll** [jernejsk/OpenELEC-OPi2#75]
Hello,

I installed openelec on an opiplus2e, its connected via HDMI to a TV screen.

EDIT:
OpenELEC-H3.arm-7.0-devel-20160806193256-r22886-g5828aec-opiplus2e.img

During boot, the screen displays the openelec logo, then it plays a sound, probably try to switch resolution, and then there's garbage on display, I can see somewhat that there's openelec displayed,
I can interact with a keyboard and it makes sounds.

The opi is hooked via network to my laptop, it gets DHCP properly, but there's no SSH to get logged onto it...

$ nmap opi

Starting Nmap 6.40 ( http://nmap.org ) at 2016-09-16 20:04 CEST
Nmap scan report for opi (192.168.1.10)
Host is up (0.0029s latency).
rDNS record for 192.168.1.10: orangepiplus2e
Not shown: 996 closed ports
PORT     STATE SERVICE
111/tcp  open  rpcbind
445/tcp  open  microsoft-ds
2045/tcp open  cdfunc
8080/tcp open  http-proxy

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

Is there some way to tell openelec not to switch resolution from the one it boot ?

BTW, I also tried armbian, and got similar display problems. Tried the factory installed
android (on eMMC) and this one gets display working...

What can I do to debug this ?

Thanks

**Comment by jernejsk** [comment]
SSH must be enabled at first run, so you would need working GUI for that. What can you do, however, is to connect serial cable to opiplus2e. That way you will get an access to a terminal, over which you can discover what resolution is set and then set it in script.bin. You could also restart Kodi and it should work too.

Is there any chance that your TV doesn't support 1080p resolution? If that is the case, you can go ahead and just set lower resolution like 720p and hope that it will work.

Automatic resolution setting is WIP.

**Comment by vincent-legoll** [comment]
Hello, thanks for the answer.

No, the TV does not support 1080p, it can do 720p/1080i/1024x768 & lower though. 

I'll try to change script.bin from my laptop, but I already tried that on armbian. I get HDMI output working but the TV displays it "too wide". I was trying openelec to see if this problem is there/not there...

I think my only solution is to wait for proper DRM / HDMI driver to hit mainline, which I'll also wait to have proper CPU freq scaling, I don't want to fry the board...

**Comment by jernejsk** [comment]
As you wish. Be aware that Allwinner didn't release proper documentation or properly licensed code which would make mainline HDMI driver possible...

**Comment by vincent-legoll** [comment]
Ah, I had the impression this was happening with jeffmoine's work , but I may have overlooked something, crap...

What I'm not understanding: is the AW released code sufficient to do a rewrite or not ?

**Comment by jernejsk** [comment]
well, jeffmoine's work is great and usable, however, the key is in "properly licensed" part of my sentence. HDMI code is under no particular license, only copyrights are asserted, which is unacceptable for mainline kernel. Atop of that, this code contains a lot of magic constants with no explanation. A lot of those values were decoded, but many were not, most notably for HDMI phy.

In short, jeffmoine's work on HDMI is usable, but it won't be merged until a) Allwinner properly license it's code, or better, b) Allwinner releases HDMI documentation.
