### ISSUE TITLE
USB webcam driver

### ISSUE THREAD

**Issue by Fedy-zz** [jernejsk/OpenELEC-OPi2#76]
How can I do recognize a generic USB webcam on OpenELEC as /dev/video0?
I attached the webcam:

```
OpenELEC:~ # lsusb
...
Bus 007 Device 002: ID 0ac8:301b Z-Star Microelectronics Corp. ZC0301 Webcam
...
```

```
OpenELEC:~ # modprobe gspca_main
OpenELEC:~ # modprobe gspca_zc3xx
modprobe: FATAL: Module gspca_zc3xx not found in directory /lib/modules/3.4.112
OpenELEC:~ # ls -sh /dev/video0
ls: /dev/video0: No such file or directory
```

I had compiled the entire image of OpenELEC. How can I compile the module gspca_zc3xx.ko only (which is missing)?

**Comment by jernejsk** [comment]
Webcams are disabled in kernel config. Only way to fix it is to add them in kernel config and rebuild whole image. What is your use case for that? With good enough reason I will add them here.

**Comment by Fedy-zz** [comment]
Hi jernej,  the goal is video streaming (eg video surveillance, combined with the very light program "mjpg_streamer" precompiled).

**Comment by jernejsk** [comment]
Don't you think that some other, general purpose, distribution would be more suitable? Armbian, for example?

**Comment by Fedy-zz** [comment]
I already use Armbian on my other orange pi pc in a room with webcam streaming, but in the other room I need both kodi with hdmi cec and webcam streaming, and your fork of OpenELEC is the only solution.

**Comment by jernejsk** [comment]
Ok, I will add them this week. I will also prepare a new image, which is long overdue.
