### ISSUE TITLE
Installation instructions for the Beelink x2

### ISSUE THREAD

**Issue by diizzyy** [jernejsk/OpenELEC-OPi2#77]
@jernejsk 
What's the installation procedure for the Beelink x2? I can't seem to find anything that's compatible with the image that's getting generated.

Awesome work overall!

**Comment by jernejsk** [comment]
You mean compiling or flashing SD card? Flashing is the same with all images, extract and use program like etcher. They can be found here: https://down.nu/images If you mean building, just specify bx2 as system type. More info on orange pi forum, under FAQ.

**Comment by diizzyy** [comment]
Ahh, I figured that you installed it on the eMMC. Thanks for the clarification.
