### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by 6ig6oy** [jernejsk/OpenELEC-OPi2#78]
Hi jernejsk,

on my Orange-pi PC, the last two versions(2016-10-26 & 2016-08-06) when loading OpenElec remains  the screen black, it does not load the GUI. Only is connected the power and the hdmi. The only solution is to reinstall the img on the SD card again.

Another minor problem is settings->System->Video Output, the rate frame is always shaded at 60fps and I can not be changed by another value. For this, I must restart the OpenElec and then I can change it to 50fps, which is how I want to leave it by default. Although when I turn on OpenElec another day, it blocks me at 60fps again, it does not save my settings.

Thank you so much
:)

**Comment by jernejsk** [comment]
This sounds like monitor issues. If you want to have any other frame rate  available than 60 Hz, you have to have HDMI connected during boot. Moreover, if EDID doesn't report any other frame rate supported or there is an issue reading it, this option will be grayed out. Try another HDMI cable?

About black screen issue - Kodi usually saves last set resolution and tries to restore it next run. Please enable SSH and provide kodi.log before and after the issue.

**Comment by 6ig6oy** [comment]
Hi jernejsk,

I'm going to change the hdmi, the same is bad and it may be causing problems.
Now I have made a copy of kodi.log, if the problem arises I will copy the new kodi.log, to facilitate you both.

Thank you so much
:)

**Comment by jernejsk** [comment]
any news?

**Comment by 6ig6oy** [comment]
Hi jernejsk,

since starting OpenElec(firm used openelec-h3.arm-7.0-devel-20161209170655-r23159-g21fd889) load the boot logo with orange, I have not the problem of the black screen. I think the problem is solved.

By the way, the "Fix WMV3 playback" works perfectly with H/W.
Now I'm going to install your last firm openelec-h3.arm-7.0-devel-20170112235053-r23261-ge328780e4.

Thank you so much for all your work.
regards
:)

**Comment by jernejsk** [comment]
Ok, then I can close the issue.
