### ISSUE TITLE
Change fex file for the Orange Pi PC 

### ISSUE THREAD

**Issue by gitchomik** [jernejsk/OpenELEC-OPi2#8]
Here is an official fex file for the Orange Pi PC 
https://github.com/linux-sunxi/sunxi-boards/blob/master/sys_config/h3/xunlong_orange_pi_pc.fex

Probably it fix problem with overheating
http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=870

**Comment by jernejsk** [comment]
This was fixed long time ago.  Granted, ths values are not completely the same, but that shouldn't cause any overheating issues. Do you think that your board overheats with existing settings?

**Comment by gitchomik** [comment]
@jernejsk
Honestly I did not check this, but I am suggesting by this comment "heatsink strongly recomended" (http://www.orangepi.org/orangepibbsen/forum.php?mod=viewthread&tid=648)

Suggested .fex was provided 11 day ago, so I though that maybe will help.

If you think that current fex it's better then suggested, feel free to close this issue.

**Comment by jernejsk** [comment]
That post is not mine and remark was valid some time ago. Correct values to prevent overheating were posted on mailing list and wiki pages weeks before this fex was published. So there is no overheating issue but some values will be syncronized in the future.

**Comment by pdefreitas** [comment]
My orange pi with the latest build is around 75ºC idle. With armbian it was only 53ºC. Is this using the same fex?

**Comment by jernejsk** [comment]
Not exactly the same, but it should be similar, especially for DVFS settings. One quick test - disable RSS feed on main screen, leave Kodi running for a while and then check temperature again.

**Comment by pdefreitas** [comment]
Recompiled with the fex mentioned before now it idles at 63/64 ºC. I will try that setting in a moment.

**Comment by jernejsk** [comment]
You mean with Armbian fex? Which settings make most of the difference?

**Comment by pdefreitas** [comment]
The fex provided by gitchomik of linux sunxi.

**Comment by jernejsk** [comment]
Ok, then please found out which settings are needed for this and then I will considered them.
