### ISSUE TITLE
show CPU temperature in system info (enhancement request)

### ISSUE THREAD

**Issue by lymon66** [jernejsk/OpenELEC-OPi2#9]
can you add the following line to advancedsettings.xml to show (correct) CPU temperature in system info:

`<cputempcommand>echo $(cat /sys/class/thermal/thermal_zone0/temp)C</cputempcommand>`

**Comment by gitchomik** [comment]
https://github.com/jernejsk/OpenELEC-OPi2/pull/13

**Comment by jernejsk** [comment]
Merged
